{"version":3,"file":"useAuthError.js","sourceRoot":"","sources":["../../../../src/react/hooks/useAuthError.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,cAAc,EAAE,MAAM,+BAA+B,CAAC;AAS/D,MAAM,UAAU,YAAY;IAC1B,MAAM,EAAE,QAAQ,EAAE,GAAG,cAAc,EAAE,CAAC;IAEtC,OAAO,CACL,CAAC,CAAC,QAAQ,CAAC,IAAI,KAAK,gBAAgB,IAAI,QAAQ,CAAC,IAAI,KAAK,aAAa,CAAC;QACtE,QAAQ,CAAC,KAAK,CAAC;QACjB,SAAS,CACV,CAAC;AACJ,CAAC","sourcesContent":["import { useAuthContext } from \"../components/auth/context.js\";\n\nexport type UseAuthErrorResult = Error | undefined;\n\n/**\n * Returns the error returned from the current auth step, if it exists\n *\n * @returns the current Error object\n */\nexport function useAuthError(): UseAuthErrorResult {\n  const { authStep } = useAuthContext();\n  // TODO: generalize this, since only passkey_verify and eoa_connect have errors right now\n  return (\n    ((authStep.type === \"passkey_verify\" || authStep.type === \"eoa_connect\") &&\n      authStep.error) ||\n    undefined\n  );\n}\n"]}